# Generated by Django 3.2.7 on 2021-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_publication_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
