# Generated by Django 3.2.7 on 2021-09-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='enddate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='startdate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
