# Generated by Django 3.2.7 on 2021-09-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210918_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['created']},
        ),
    ]
