# Generated by Django 3.2.7 on 2021-09-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210925_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-no']},
        ),
    ]
