# Generated by Django 3.2.7 on 2021-10-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210928_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
