# Generated by Django 3.2.7 on 2021-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='')),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=2000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
