# Generated by Django 3.2.7 on 2021-10-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='mainImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
