# Generated by Django 3.2.7 on 2021-12-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211004_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=60)),
                ('contactEmail', models.EmailField(max_length=300)),
                ('contactSubject', models.CharField(max_length=200)),
                ('contactMessage', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
