# Generated by Django 3.2.3 on 2021-12-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211219_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='source_link',
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
