# Generated by Django 3.2.3 on 2021-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211231_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='lab_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
