# Generated by Django 3.2.3 on 2021-12-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211231_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='lab_link',
        ),
        migrations.RemoveField(
            model_name='work',
            name='lab_name',
        ),
    ]
