# Generated by Django 5.2.3 on 2026-05-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_update_info_short_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publication_link',
        ),
        migrations.RenameModel(
            old_name='Reference',
            new_name='RelatedPublication',
        ),
        migrations.AlterModelOptions(
            name='relatedpublication',
            options={
                'ordering': ['created'],
                'verbose_name': 'Related publication',
                'verbose_name_plural': 'Related publications',
            },
        ),
        migrations.AlterField(
            model_name='relatedpublication',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='related_publications',
                to='home.project',
            ),
        ),
    ]
