# Generated by Django 5.2.3 on 2026-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_info_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
