# Generated by Django 5.2.3 on 2026-06-15 06:19

from datetime import datetime

from django.db import migrations

DATE_FORMATS = ("%b %Y", "%B %Y", "%Y")
PRESENT_VALUES = frozenset({"present", "current", ""})


def _parse_date_string(value):
    """Parse a legacy date string into a date, or return None if unparseable."""
    if value is None:
        return None
    stripped = value.strip()
    if not stripped:
        return None
    for fmt in DATE_FORMATS:
        try:
            return datetime.strptime(stripped, fmt).date().replace(day=1)
        except ValueError:
            continue
    return None


def _is_present(value):
    """Return True when a legacy end-date string means an ongoing role."""
    if value is None:
        return True
    return value.strip().lower() in PRESENT_VALUES


def backfill_work_dates(apps, schema_editor):
    Work = apps.get_model("home", "Work")
    for work in Work.objects.all():
        start_date = _parse_date_string(work.startdate)
        if work.startdate and start_date is None:
            print(
                f"WARNING: Could not parse startdate '{work.startdate}' "
                f"for Work id={work.pk} title='{work.title}'"
            )

        if _is_present(work.enddate):
            end_date = None
        else:
            end_date = _parse_date_string(work.enddate)
            if work.enddate and end_date is None:
                print(
                    f"WARNING: Could not parse enddate '{work.enddate}' "
                    f"for Work id={work.pk} title='{work.title}'"
                )

        work.start_date = start_date
        work.end_date = end_date
        work.save(update_fields=["start_date", "end_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_work_date_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_work_dates, migrations.RunPython.noop),
    ]
