# Generated by Django 5.2.3 on 2026-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_backfill_work_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': [models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), '-start_date']},
        ),
        migrations.RemoveField(
            model_name='work',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='work',
            name='startdate',
        ),
    ]
