# Generated by Django 5.2.14 on 2026-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_seed_tech_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), '-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='projects', to='home.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='openalex_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('openalex', 'OpenAlex')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
