# Generated by Django 5.2.14 on 2026-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_publication_metadata_and_project_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='openalex_author_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
